[tools]
node = "latest"
hugo = { version = "latest", postinstall = "hugo completion zsh > /usr/local/share/zsh/site-functions/_hugo" }

[tasks.server]
description = "Run development server"
run         = "hugo server -D"
alias       = "s"

[tasks.build]
description = "Build site"
run         = "hugo build"
